### ISSUE TITLE
Vorbereitung der NWBib-Integration

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#163]
Currently, the "old" Aleph-based NWBib is searched within the Virtuelle Deutsche Landesbibliograhie (VDL). In order to ultimately switch to the new interface at some point, searches oin VDL also have to be served by the new system. 

As long as the description of VDL technology (which is based on the KVK, Karlsruher Virtueller Katalog) on Wikipdia (https://de.wikipedia.org/wiki/Karlsruher_Virtueller_Katalog#Technologie) is still up-to-date, it might be quite easy to switch by adjusting the VDL configuration file for NWBib.

I will contact Uwe Dierolf, (kvk@bibliothek.kit.edu) and ask him whether this is doable.

**Comment by acka47** [comment]
> I will contact Uwe Dierolf, (kvk@bibliothek.kit.edu) and ask him whether this is doable.

Did that today. Now waiting for a response.

**Comment by acka47** [comment]
Got the response and also phoned with Uwe Dierolf. The general process for getting the new NWBib website into VDL looks like this:

1. Sort out financing as integration of a new source in VDL costs 2,500 Euros.
2. Settle on a final URL where NWBib will be found.
3. put together the following info for VDL integration:
a. what lobid API calls should be used
b. how the result list should be parsed
c.  how VDL should link back to NWBib
4. voilà, the new NWBib website can replace the old one in VDL.

**Comment by acka47** [comment]
We should also switch to SSL before this.

**Comment by fsteeg** [comment]
Tagging as `nwbib-launch`. Is this correct, @acka47?

**Comment by acka47** [comment]
At least G.C. doesn't think this is important for the launch. Thus, moved to backlog.

**Comment by acka47** [comment]
Ich mach mal auf Deutsch weiter. Habe heute den E-Mail-Thread mit @udgithub (U. Dierolf) wieder aufgegriffen und beginne nun, Antworten auf die oben gelisteten Fragen zu finden.

1. Sort out financing as integration of a new source in VDL costs 2,500 Euros. :white_check_mark: 
2. Settle on a final URL where NWBib will be found. :white_check_mark: -> https://nwbib.de 
3. put together the following info for VDL integration:
   a. what lobid API calls should be used:
   b. how the result list should be parsed
   c.  how VDL should link back to NWBib
4. voilà, the new NWBib website can replace the old one in VDL.

In Bezug auf 3.a) und mit Blick auf die Suchmaske unter http://kvk.bibliothek.kit.edu/vdl/, müssen wir offensichtlich API Calls für die folgenden Suchanfragen auflisten (ich benutze `{searchterm}` als Variabel für den Suchbegriff):

- Titel: http://lobid.org/resources/search?q=title:{searchterm}+OR+otherTitleInformation:{searchterm}
- Autor: Wenn ich das richtig sehe, können wir noch nicht per URL Beitragende vom Typ `Person` abfragen und müssen dafür wahrscheinlich noch einen Parameter ergänzen.
- Körperschaft: ebenso, nur mit `CorporateBody`
- Jahr: http://lobid.org/resources/search?q=publication.startDate:{searchterm}
- Sachbegriff-Suche: Ich glaube, wir können gerade auch nicht ohne weiteres Schlagwörter nach Typ abfragen und müssen auch dafür einen Parameter ergänzen.
- Person als Schlagwort: ebenso
- Ort / Region: Es gibt verschiedene Felder, in denen Informationen zu Orten / Regionen als Schlagwort stehen. Wir müssen dafür wohl eine Suche in a) `spatial` und in b) `subject` mit source `http://purl.org/lobid/nwbib-spatial` mit einer Suche in c) den GND-Schlagwörtern vom Typ "Geographika" kombinieren. (Dafür sollte #130 fertig implementiert sein.) Soweit ich weiß, können wir per URL gerade nur a) machen.

Mir war nicht klar, dass die VDL eine so differenzierte Suche ermöglicht. Wie es aussieht müssen wir erst noch einige Anpassungen an der API vornehmen, bevor wir die Integration umsetzen können. Allerdings handelt es sich bei den meisten Anforderungen um Dinge, die ohnehin für die NWBib-Oberfläche nötig sind und also spätestens bei einem Umstieg der NWbib auf API 2.0 hätten umgesetzt werden müssen.

**Comment by acka47** [comment]
Heute kam per E-Mail eine Anfrage aus der ULB Düsseldorf zur NWBib, ob wir in Sachen VDL-Integration wieder tätig werden könnten. Wir sollten also einen konkreten Plan zur Umsetzung besprechen, gerade in Bezug auf den Umstieg zu API 2.0 im Rahmen der erweiterten Ortssystematik.

**Comment by fsteeg** [comment]
Erforderliche Schritte für die VDL-Integration:

- [ ] Suchen aus https://github.com/hbz/nwbib/issues/163#issuecomment-315118385 auf Basis von API 2.0 implementieren
- [ ] Suchergebnis als JSON von API durchreichen

Weitere Schritte einer kompletten API-2.0-Umstellung, nicht für VDL-Integration erforderlich:

- [ ] Einzeltreffer-Ansichten
- [ ] Geosuche (Karte auf der Hauptseite)
- [ ] Themensuche

**Comment by acka47** [comment]
Wir haben uns beim NWBib-Treffen auf folgendes Vorgehen geeinigt: Umsetzung der NWBib auf Basis von lobid-API 2.0 bis Jahresende (siehe https://github.com/hbz/nwbib/milestone/3), dann Übergabe an KVK.

**Comment by fsteeg** [comment]
Anfragen entsprechend https://github.com/hbz/nwbib/issues/163#issuecomment-315118385:

Titel, Autor, Körperschaft, Jahr:

- [ ] http://test.nwbib.de/search?format=json&name=Schmitz
- [ ] http://test.nwbib.de/search?format=json&person=Schmitz
- [ ] http://test.nwbib.de/search?format=json&corporation=Schmitz
- [ ] http://test.nwbib.de/search?format=json&issued=1999

Schlagwörter (Sachbegriff, Person, Ort/Region):

- [ ] http://test.nwbib.de/search?format=json&subject=Wald
- [ ] http://test.nwbib.de/search?format=json&subject=Schmitz
- [ ] http://test.nwbib.de/search?format=json&subject=Eifel

So weit der aktuelle Stand.

Die `person=` Anfrage sucht in `contribution.agent` allgemein, was das ist, was ich erwarten würde beim Feld "Autor" in der VDL (ich würde da auch eine Körperschaft eingeben z.B.). Um das deutlicher zu machen könnten wir den Parameter `author` oder  `agent` nennen.

Die 3 `subject` Anfragen entsprechen der aktuellen Umsetzung in  der VDL, die auch bei allen die gleiche Suche macht. Mit unseren `nested` Anfragen könnten wir hier auch differenzierter Suchen, wie bei `corporation`, aber wollen wir das?

**Comment by acka47** [comment]
- Der `name`-Parameter sollte sowohl das "title"-Feld als auch "otherTitleInformation" abfragen, z.B. http://test.nwbib.de/search?format=json&name=Schmitz sollte die gleichen Ergebnisse bringen wie http://lobid.org/resources/search?q=(title%3Aschmitz+OR+otherTitleInformation%3Aschmitz)+AND+inCollection.label%3ANWBib&format=json
- Der `person`-Parameter sollte nur `contribution.agent.label` von Objekten mit `"type": "Person"` abfragen.
- Die Körperschaftssuche sieht gut aus.
- Die Jahr-Suche sieht auch gut aus. (Die geht wahrscheinlich einfach auf `publication.startDate`, womit dann auch `SecondaryPublicationEvent`s abgefragt werden. Sinnvoller wäre hier wohl die Suche auf `"type": "PublicationEvent"` einzuschränken, was aber eine weitered "nested"-Suche bedeuten würde.)
- Die Schlagwortsuche sollte auch auf `subjectAltLabel`, was gerade noch nicht der Fall ist.

**Comment by fsteeg** [comment]
Deployed to test:

- [ ] https://test.nwbib.de/search?format=json&subject=Turmwindmühle
- [ ] https://test.nwbib.de/search?format=json&name=schmitz
- [ ] https://test.nwbib.de/search?format=json&person=schmitz

**Comment by acka47** [comment]
Looks good. One last thing. We should also query the variant names for a person, e.g. https://test.nwbib.de/search?format=json&person=Chainrich should give results with works bei Heinrich Böll and Heine, see e.g. this entry http://lobid.org/resources/HT019390435.json

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/search?format=json&person=Chainrich

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Was automatically closed by merging #413. Reopened again.

**Comment by ChristophEwertowski** [comment]
+1 Wenn ich es richtig sehe, fehlt noch die Schlagwortsuche auf die `subjectAltLabel`, oder @acka47 ?

**Comment by acka47** [comment]
> Wenn ich es richtig sehe, fehlt noch die Schlagwortsuche auf die `subjectAltLabel`, oder @acka47 ?
  
Das funktioniert, siehe z.B. https://test.nwbib.de/search?format=json&subject=Krankheitszustand

**Comment by acka47** [comment]
Offensichtlich ist die neue Version schon auf Production deployt, ohne dass wir das nochmal gründlich gereviewt hätten. So kam heute eine Meldung aus der Redaktion rein:

On 1/3/18 8:39 AM, E. L. wrote:
> einige Anfragen in der NWBib Webversion laufen zurzeit fehlerhaft. Hier 
> zwei zufällig gefundene Beispiele.
> 
> Die konkrete  Titelsuche „Kommunales Management für Familien in einer 
> kreisangehörigen Stadt“ zeigt 198227 Treffer an. 
> https://nwbib.de/search?sort=newest&name=kommunales+management+f%C3%BCr+familien. 
> Das kann nicht sein.
> 
> Mit dem SW „Landwirtschaft“ kann ich eine Trefferliste von 2078 Titeln 
> generieren https://nwbib.de/search?sort=newest&subject=landwirtschaft. 
> Will ich die Liste mit Kreisen (223) facettieren, erscheint der 
> Programmiertext statt einer Trefferliste.
> 
> Gibt es dafür einen Grund? Wir hatten bereits aus der Information 
> Rückfragen.

@dr0i Kannst du das bitte morgen direkt auf die alte Version zurückstellen?

**Comment by acka47** [comment]
Herr F. hat sich nun auch gemeldet und zwei Probleme angemerkt. Hier eine Liste mit den obigen beiden Punkten und F.'s neuen:

- [ ] Suchterme mit Bolleschem AND als default verknüpfen (https://test.nwbib.de/search?sort=newest&name=kommunales+management+f%C3%BCr+familien sollte das gleiche Ergebnis geben wie https://test.nwbib.de/search?sort=newest&name=kommunales+AND+management+AND+f%C3%BCr+AND+familien)
- [ ] Das Klicken auf ein Facettenfilter gibt JSON anstatt HTML zurück
- [ ] Sachsystematikstellen werden doppelt angezeigt unter "Sachsystematik" und "Schlagwörter", siehe z.B. https://test.nwbib.de/HT019480641
- [ ] Die Notationen werden bei den Sachstematikstellen nicht angezeigt (Herr F. hat mich deshalb angerufen.) Das sollte so aussehen wie in der alten Version, z.B. https://nwbib.de/HT019480641

Jetzt schau ich nochmal selbst durch und mach eine weitere Liste. Ist sehr überfrachtet das Ticket. Wenn gewünscht, kann ich auch einzelne Issues aufmachen...

**Comment by dr0i** [comment]
Ja, mein Fehler. Ist nun zurückgedreht.

**Comment by acka47** [comment]
- [ ] Zwei Suchterme in der Erweiterten Suche nach "Person" funktionieren nicht, vgl. https://test.nwbib.de/search?sort=newest&person=b%C3%B6ll vs. https://test.nwbib.de/search?sort=newest&person=heinrich+b%C3%B6ll
- [ ] Suchterme sollten auch in der erweiterten Suche mit Booleschem AND verknüpft sein, vgl. https://test.nwbib.de/search?name=&person=&subject=m%C3%BCll+d%C3%BCsseldorf und https://nwbib.de/search?name=&person=&subject=m%C3%BCll+d%C3%BCsseldorf
- [ ] ISBN-Suche mit Bindestrich funktioniert nicht, vgl. https://nwbib.de/search?sort=newest&id=+978-3745061994 und https://test.nwbib.de/search?sort=newest&id=+978-3745061994
- [ ] `bibliographicCitation` sollte bei einer Standardsuche nicht durchsucht werden, siehe https://github.com/hbz/nwbib/issues/110
-  [ ] Suche nach Personen via GND (ob mit oder ohne Bindestrich) funktioniert nicht, z.B. http://test.nwbib.de/search?person=10007642-7 oder https://test.nwbib.de/search?name=&person=118926179
- [ ] Die Trefferangabe beim Paging von Einzeltreffern ist immer auf Null.  
- [ ] Eine Schlagwortuche mit `,` gibt keine Ergebnisse, z.B. https://test.nwbib.de/search?name=&person=&subject=b%C3%B6ll%2C+heinrich (siehe auch https://github.com/hbz/nwbib/issues/151)
- [ ] Wir sollten Verschlagwortung mit `"source.label": "Dewey-Dezimalklassifikation"` besser gar nicht anzeigen. Vgl. http://test.nwbib.deHT006984941 (das auch einige offensichtlich falsche DDCs hat) mit https://nwbib.de/HT006984941
- [ ] Die Merkliste funktioniert gerade bei mir gar nicht, z.B. https://test.nwbib.de/stars?ids=BT000098085%2CHT003884233%2CBT000102052%2CHT019322397%2CHT019320896%2CHT019320937%2CHT019325063%2CHT019325531
- [ ] Bei den Links zu den Bänden, insbesondere der Zählung gibt es Unstimmigkeiten, z.B. https://test.nwbib.de/HT003001232 & https://test.nwbib.de/HT006984941

Ich glaube das reicht erstmal. Die Systematiken kann ich gerade nicht testen, weil es keine Labels auf dem Testsystem gibt...

**Comment by fsteeg** [comment]
Die Systematiken sind wieder im Testsystem: https://test.nwbib.de/search

**Comment by fsteeg** [comment]
I've started fixing the issues mentioned in the comments above.

@acka47 I suggest this approach: I check the boxes above when fixes are deployed to test, and you strike out the text next to the box when review is complete to confirm the fix.

**Comment by fsteeg** [comment]
All boxes checked, ready for review.

**Comment by acka47** [comment]
Ich habe jetzt alle Punkte durchgestrichen, allerdings ist die automatische UND-Verknüpfung noch nicht komplett umgesetzt, dazu kommen ein paar neue Punkte:

- [ ] Die automatische Und-Verknüpfung wurde fast überall umgesetzt, fehlt aber noch in der allgemeinen Suche. (vgl. https://test.nwbib.de/search?location=&q=k%C3%B6ln+karneval & https://nwbib.de/search?location=&q=k%C3%B6ln+karneval)
- [ ] Wie es aussieht nutzen wir in Production Stemming auch bei allen Feldern der erweiterten Suche, in der neuen Version aber im Feld "Verlag" noch nicht. Vergleiche z.B.  https://test.nwbib.de/search?sort=newest&publisher=westf%C3%A4lisches+dampfboot & https://nwbib.de/search?sort=newest&publisher=westf%C3%A4lisches+dampfboot, wo die zweite Anfrage auch Titel mit "Westfäl. Dampfboot" (z.B. https://nwbib.de/HT013219523) enthält.
- [ ] Eine "ab Erscheinungsjahr x"-Suche funktioniert in der neuen Version noch nicht, vgl. https://test.nwbib.de/search?issued=2015- & https://nwbib.de/search?sort=newest&word=2015-

Wohlgemerkt, mir sind auch einige Dinge aufgefallen, die in der neuen Version besser sind! Ich glaube mit den letzten hier genannten Anpassungen (vor allem dem ersten Punkt) plus einer Verschnellerung der Themensuche können wir das Launchen zum Testen durch die Redaktion.

**Comment by fsteeg** [comment]
> Ich glaube mit den letzten hier genannten Anpassungen (vor allem dem ersten Punkt) plus einer Verschnellerung der Themensuche können wir das Launchen zum Testen durch die Redaktion.

- [ ] Das hatte ich nirgends explizit erwähnt glaube ich, aber die Themensuche ist schon umgestellt.

**Comment by acka47** [comment]
Ok, als ich es gestern ausprobiert hatte, kam es mir noch sehr langsam vor. Vielleicht habe ich aber auch einfach nicht richtig aufgepasst. Dann werde ich mal eine E-Mail an die Redaktion schreiben.

**Comment by fsteeg** [comment]
@acka47 Habe die verbleibenden Häkchen gesetzt, siehe auch edits bei den einzelnen Punkten.

**Comment by acka47** [comment]
Ich würder sagen, das kann dann auf Production deployed werden und wir lassen die NWBib-Redaktion begutachten.

**Comment by acka47** [comment]
Wie gerade besprochen:

- [ ] Die Query beim Klick auf ein(e) Schlagwort(folge) in der Themesuche sollte auf `subject.label` anstatt generell auf `subject` gehen.

**Comment by fsteeg** [comment]
Habe außer DDC die Punkte oben abgehakt.

Die DDC-Sonderbehandlung bringt im Zusammenspiel mit der Themensuche leider total viel Komplexität rein: neben der schon umgesetzen Sonderbehandlung bei der Anzeige brauchen wir spezielle Queries (bisherige funktionieren nicht weil wir hier wieder einen neuen, speziellen Fall haben, nämlich nested auf `subject` um den Typ zu filtern ODER normal in `subjectAltLabel`). Dazu kommt dann noch die spezielle Aggregation, um da auch die DDC subjects nested zu filtern (sicher nicht performanter als die bisherige, einfache Aggregation).

Ich denke wir sollten:

- entweder DDC subjects wie andere behandeln, d.h. sie werden angezeigt und tauchen in Schlagwortsuche und Themensuche auf
- oder wir nehmen für Schlagwortfolgen doch ein eigenes Feld wie `subject.summary`, und die Themensuche operiert nur darauf

**Comment by acka47** [comment]
Zwei Punkte habe ich oben bereits durchgestrichen.

Was die Sache mit dem fehlenden `endDate` bei `SecondaryPublicationEvent` von `Periodical`s angeht, bin ich immer noch der Meinung, dass der bis-Strich nicht angezeigt werden sollte. Es handelt sich da ja nicht um eine fortlaufende Publikation, sondern um die nachträglich Publikation eines bestehenden Periodikums, dessen Publikation meist eingestellt ist. Von daher wird es in der Regel besser sein, wenn es als einzelnes Publiaktionsdatum ohne "bis" angezeigt wird.

Zur DDC: Wir lassen das erstmal einfach so und schauen, ob sich jemand beklagt.

Die Sache mit den Umlauten teste ich dann, wenn es deployed ist.

**Comment by fsteeg** [comment]
> Was die Sache mit dem fehlenden endDate bei SecondaryPublicationEvent von Periodicals angeht, bin ich immer noch der Meinung, dass der bis-Strich nicht angezeigt werden sollte. Es handelt sich da ja nicht um eine fortlaufende Publikation, sondern um die nachträglich Publikation eines bestehenden Periodikums, dessen Publikation meist eingestellt ist. Von daher wird es in der Regel besser sein, wenn es als einzelnes Publiaktionsdatum ohne "bis" angezeigt wird.

Auf test deployed, secondary publications werden nie als range angezeigt, siehe:
https://test.nwbib.de/HT016401113 und https://stage.lobid.org/resources/HT016401113

**Comment by acka47** [comment]
+1 Wie gesagt muss ich die Umlautsuchen aber noch austesten, wenn es deployt ist.

**Comment by acka47** [comment]
As discussed offline, we now decided to show the DDC labels + notations in NWBib as well as in lobid.org. This should be no problem as we have the information in the respective `Subject` object, e.g.

```json
{
  "subject":[
    {
      "label":"Künste",
      "notation":"700",
      "source":{
        "id":"http://d-nb.info/gnd/4149423-4",
        "label":"Dewey-Dezimalklassifikation"
      }
    },
    {
      "label":"Biografien",
      "notation":"709.2",
      "source":{
        "id":"http://d-nb.info/gnd/4149423-4",
        "label":"Dewey-Dezimalklassifikation"
      }
    }
  ]
}
```

**Comment by acka47** [comment]
Umlautsuche ist auch ok. Dann fehl nur noch die DDC-Anzeige...

**Comment by fsteeg** [comment]
DDC-Anzeige und Gruppierung ist deployed:

https://test.nwbib.de/HT016604323
https://test.nwbib.de/HT009821451
https://test.nwbib.de/HT018239864

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Reopened for the actual VDL integration and because this still is on the test system.

**Comment by fsteeg** [comment]
Nächste Schritte auf Basis der Mail von H.F. vom 16.2.:

- [ ] In jeder Titelanzeige sollte der Link zum hbz-Katalog verankert bleiben
- [ ] Name der Bibliographie als Info und Markenzeichen auch auf der Seite der Volltitelanzeige
- [ ] Könnte der Sachtitel nicht auch in der in der TA hervorgehoben werden?
- [ ] Wir halten es eher für irritierend, wenn bei Monographien sporadisch DDC-Stellen auftauchen
- [ ] Link von der Schlagwortfolge des gefundenen Titels zu gleich beschlagworteten Titeln
- [ ] Schlagwortsuche: nur Norm- und Freitexteinträge Aleph-Felder 902 ff. und 400er GND-Felder
- [ ] Themensuche: nur Norm- und Freitexteinträge Aleph-Felder 902 ff. und 400er GND-Felder

Über die aktuell produktive Funktionalität hinausgehende Aufgaben (nach API-Umstieg und VDL-Integration, d.h. sollten in separate Tickets ausgelagert werden):

- [ ] Bei mehr als zwei Treffern zu einer SWF: „X weitere Treffer zum Thema“, verlinken
- [ ] Themensuche: Möglichkeiten zur erweiterten Ausschöpfung der GND-Schlagwortrelationen
- [ ] Anzahl der Titel zu einer Themenfolge anzeigen
- [ ] Themenfolgen könnten in einen Gesamtindex von Sacherschließungselementen einfließen

**Comment by fsteeg** [comment]
@acka47 Habe die Änderungswünsche umgesetzt, siehe die Liste oben. Ich habe ein paar pragmatische Kompromisse gemacht um hier voranzukommen, speziell mit der ja inzwischen auch von extern geforderten VDL-Integration. Ich glaube das ist ein guter Stand mit vielen Verbesserungen gegenüber der aktuell produktiven Version. Weitere Anpassungen könne wir ja auch nach dem API-Umstieg umsetzen.

**Comment by acka47** [comment]
+1 Mail an die NWBib-Redaktion ging gestern raus.

**Comment by fsteeg** [comment]
Kein Stemming für Subject-Queries: https://test.nwbib.de/search?subject=lohn

**Comment by acka47** [comment]
Das können wir so deployen und dann mal an dem eigentlichen Thema des Tickets arbeiten. ;-)

**Comment by fsteeg** [comment]
Deployed to production: https://nwbib.de/

**Comment by acka47** [comment]
Ich habe das Ticket umbenannt, damit wir es endlich mal schließen können. Öffne ein neues für die tatsächliche Integration.
